### PR TITLE
Bevy Rewrite

### PR DESCRIPTION
**Pull request by zicklag**
Here goes nothing. :wink: 

### Web Demo

Here's a web demo that auto-follows this branch:

https://jumpy.zicklag.spicy-lobster.katharostech.com/player/bevy-rewrite/

### CODE REVIEW

**Comment by zicklag** [comment]
Got the main menu working.

Next is the character select menu, and then map select menus.

image
image

**Comment by zicklag** [comment]
Got basic player selection screen. Needs some work, but it's good enough to move onto map loading.

https://user-images.githubusercontent.com/25393315/192618611-f4cde507-35aa-42d7-ad56-a2c66111037f.mp4

**Comment by erlend-sh** [comment]
Excellent!

We should start delving into the [netcode](https://github.com/fishfolks/punchy/discussions/217) (and subsequent [Ultimate integration](https://github.com/fishfolks/punchy/issues/153)) as soon as is fitting.

**Comment by zicklag** [comment]
Got it. Networking is a requirement for shipping right? Or should we try to get a local-only version shippable first?

If it's required for shipping then I'd put effort into that earlier rather than if we wanted to just get a local version first.

**Comment by erlend-sh** [comment]
Yeah online version has highest priority now. Local was more important when playtesting was the primary objective, but now we’re going for production-ready MVP.

**Comment by zicklag** [comment]
Making progress on the editor UI and was able to theme Egui's default widgets so that it doesn't stick out as separate from the game as much.

image

**Comment by zicklag** [comment]
Got more of the editor workflow worked out. The editor can display the bevy world ( map loader coming soon ) and control the bevy camera, zooming in and out and panning. You can also click the play button to instantly switch to playing the game on that map. Then from the pause menu, you can go back to editing the map.

Oh, and I also added a background pan-and-zoom effect to the main menu. The effect started on accident while I was testing camera zoom, and then my brother said "oh that could look good". It might need tweaking, but I think it does kind of give an underwater feel a little bit.

I need to make the parallax work later, because for now it's just static.

Also, the background panning is implemented with a scripting using the scripting API, so it's super easy to change and can be modified per custom asset pack without modifying the game.

https://user-images.githubusercontent.com/25393315/193168203-6d249216-cb82-4471-96a7-6004b3969acd.mp4

**Comment by zicklag** [comment]
Getting a better grip on the UI: did some organization and now I've got the map creation dialog:


https://user-images.githubusercontent.com/25393315/193379955-b0397c1b-4524-434b-bc5b-8f98175ce43d.mp4

Now that I've got the foundational UI and dialog structure in place, it shouldn't be too long before I've got the map layer creation and configuration working.

**Comment by zicklag** [comment]
Didn't get much time for this today, but I did get a map grid rendering, and `bevy_prototype_lyon` which I used for the grid will be useful for collision shape debug rendering, too.

https://user-images.githubusercontent.com/25393315/193434527-c95240b3-6996-4797-93f3-adba5e01fa93.mp4

**Comment by zicklag** [comment]
Got the layer creation window and layer list made:

image

Soon I should have map layers rendering.

**Comment by zicklag** [comment]
Just finished a script that converts the old maps to the new format. That should save us some work and now we should have something to render.

Immediate next steps:

- [ ] Get tiles from the ported maps rendering in the game
- [ ] Get parallax background rendering for the map
- [ ] Get map items and decorations spawning

---

Also @erlend-sh, what's a good deadline to attempt for finishing the whole MVP? I want to set a specific date to work towards.

**Comment by erlend-sh** [comment]
Ideally we’d have a functional (playable) MVP done by early November, so that we can dedicate most of November to polish and juicing ahead of the prospective crowdfunding event in December.

**Comment by zicklag** [comment]
Got a map rendering! Still plenty of work to do.

image

**Comment by zicklag** [comment]
I got map kinks worked out now, and all of the maps have been migrated.

I also got the background spawning, but I'll have to make my own parallax system because `bevy_parallax` only supports horizontal parallax. Shouldn't be too big a deal, though, I don't think. I'm going to come back to that after working on getting map decorations spawning.

image

**Comment by zicklag** [comment]
Today I got map elements basically spawning, but doing absolutely nothing, so that doesn't mean much visibly. I tweaked some of the map element metadata so I'm almost ready to get a functional map item.

Most of the work today when into allowing scripts to create Bevy components with https://github.com/jakobhellermann/bevy_mod_js_scripting/pull/26.

To clarify is _not_ just for modding. My plan is to have all map elements spawned with scripts that add the necessary bevy components. So we may use scripts in a way that is conceptually similar to Bevy scenes. This makes it super easy for us to add new kinds of items and tack on different functionality by specifying different components to add to the element, and it means that we don't have to hard-code a new item kind into the YAML format every time we add a new item.

---

Now that that's working, I'll work on getting the seaweed item created, which should be very simple. It will just be an item that get's spawned with an animation clip component.

After that I think I'll add collisions to the tile maps and spawn a player into the scene. Then, I work on the character controller.

Finally, that's probably a good time to delve into the networking code.

Once we sort out networking in it's basic form, then we can create the weapon items, and get some form of actual gameplay going.

**Comment by Zac8668** [comment]
Discussion from discord
> I was actually working on something similar, and I tried using rapier polylines(I think you're using rapier too?), not sure if that even brings some benefit but I wanted to share, the result is something like this, without the unnecessary inside colliders, maybe that's better? it needs a collider "update" everytime you change the tiles tho

image

**Comment by zicklag** [comment]
Finished migrating the physics engine from the old Jumpy! I just have to add collision shape debug rendering, and then I'm on to developing the character controller and state machine.

It will be mostly copied from the [state machine](https://github.com/fishfolks/punchy/wiki/Fighter-State-Machine) designed for Punchy, but the goal is to have all states implemented in scripts.

Because of the temporary limitation that scripts cannot create new components yet, we will probably represent the current state with a string, instead of a marker component, and then we can migrate to the more ECS-like solution once that restriction is lifted.

**Comment by zicklag** [comment]
I think I've finished off the MVP matchmaking server! It can spin up Bevy game servers on demand, in response to requests to join games of a given number of players.

The QUIC network transport used to communicate with the matchmaking server now has Bevy resources for easily sending and receiving messages in the game systems and I'm ready to start working on the in-game flow of joining an online match, picking your player, and getting into the game!

**Comment by zicklag** [comment]
Implemented matchmaking in the UI:

https://user-images.githubusercontent.com/25393315/197656921-f7dbb43c-78ca-4e7a-ad9e-7696d79763f7.mp4

Next up, player selection.

**Comment by zicklag** [comment]
Player selection done!

https://user-images.githubusercontent.com/25393315/197888752-e58b1d8e-f2a9-4743-815c-c20eb2f3cffa.mp4

Next up, map select, and then starting the game.

**Comment by zicklag** [comment]
Map selection works now:


https://user-images.githubusercontent.com/25393315/197927988-c9f90ae5-d286-4a6c-8a07-f990e57d080a.mp4

Now I get the game syncing again.

**Comment by zicklag** [comment]
Got swords and sproingers working:

[death-animation.webm](https://user-images.githubusercontent.com/25393315/199874533-30f4be27-d392-4d13-8482-53eecc5f1d16.webm)

sword-swing
Peek 2022-11-03 20-58

Making good progress!

**Comment by zTecna** [comment]
diverboot (32x9)

**Comment by zTecna** [comment]
diverboot sheet
I used the character's sprite to make the sheet

**Comment by zicklag** [comment]
Perfect, that's exactly how I need it. Thanks!

**Comment by sailormoon** [comment]
Love your project -- I'm curious why you decided to rewrite into Bevy instead of Macroquad. I'm currently evaluating engines for a 2D game I'm writing.

**Comment by zicklag** [comment]
I haven't used macroquad myself very much at all, so I can't speak to it directly, but the previous lead developer on Jumpy did, and was feeling some limitations with it, and ended up starting work on a custom renderer for it. I'm not sure what the complete story as far as the limitations were.

As far as why I wanted to use Bevy, I like that Bevy is powerful and extremely modular so I knew I could write a plugin for anything that I might need that it didn't have. It has gotten a lot of attention, has some people behind it with good ideas, and it's continued to develop and get better and better quite quickly.

The disadvantage to using Bevy is that it is more complicated, and you may have to work out some things yourself or find plugins for some things that aren't easily built in yet. Bevy is also under heavy development, so you have to be read to update your code when they make changes to the engine. ( some of this points may apply to other engines, too, though )

Notably, for Jumpy, we have just about moved it away from using Bevy directly, and are now building it on top of our own [Bones](https://github.com/fishfolk/bones) engine. There were a few things that we needed that weren't being provided easily with Bevy and it motivated us to write our own ECS and framework:

- Determinism and snapshotting - used for rollback networking support
- Easy hierarchical asset loading and user asset packs
- Easy multi-world support so you can change between menus and different parts of the game cleanly.
- Scripting support for making mods

Jumpy is already using Bones ECS to get deterministic snapshot and restore, but it is still using Bevy at the same time for the main menu and other stuff outside of the main game loop. I've just recently finished the bones asset loader and foundation for scripting, and now we're in the progress of moving Jumpy completely over to the Bones framework so that it won't be using Bevy directly anymore.

The Bones framework still uses Bevy in the background to do rendering, audio, windowing, and input, but the bones framework is technically renderer agnostic and could actually run on top of something like Macroquad.

The idea with Bones is to be more opinionated and simple than Bevy and have everything we need to make 2D games like Jumpy. We want the developer experience to be as nice as possible, while balancing with simplicity, power, and performance, roughly in that order.

The Bones framework is _nearly_ ready for other people to use it I think. As soon as I finish getting Jumpy completely ported to it, which is my top priority right now, it will be in a state where other projects should be able to use it, you wanted to try it out. It's extremely new, so there will be some rough edges, but at the same time, Jumpy will be using it, so it proves that it can actually make a game, and you can check out the Jumpy code if you want to see what a game in it looks like.

---

Another recently released option worth looking at is [Comfy](https://github.com/darthdeus/comfy). It looks like a good option for starting a 2D game, and it is probably simpler than Bones, maybe more similar to macroquad. While macroquad and comfy ( as I understand ) probably give you simple ways render basic stuff like sprites, etc. in whatever way you want, Bones works more like a mini Bevy, being built around an Entity Component System ( ECS ), and that being the way that you interact with the engine.

---

I hope that helps! If you have any more questions I'm happy to help, you can ask here, or you can also join the Discord server, where I'm often available.

**Pull request merged**
